name: "yolo26n_seg"
platform: "tensorrt_plan"
max_batch_size: 1

input [
  {
    name: "images"
    data_type: TYPE_FP32
    dims: [3, 512, 512]
  }
]

output [
  {
    name: "output0"
    data_type: TYPE_FP32
    dims: [300, 38]
  },
  {
    name: "output1"
    data_type: TYPE_FP32
    dims: [32, 128, 128]
  }
]

instance_group [
  {
    kind: KIND_GPU
    count: 1
  }
]

dynamic_batching {
  preferred_batch_size: [1]
  max_queue_delay_microseconds: 0
}
